<template>
  <div>
    <form @submit.prevent="addVendor" class="mt-4 px-3 pb-2">
      <!-- Name Section here  here -->
      <div class="grid grid-cols-2 gap-4 mb-4">
        <div class="col-span-1">
          <label for="plan-name" class="font-medium block text-base mb-2">
            Plan Name
          </label>
          <input
            type="text"
            id="plan-name"
            placeholder="Plan Name"
            v-model="payload.name"
            class="text-base p-4 rounded-md font-normal w-full outline-none ring-0 bg-[#FAFAFA]"
          />
        </div>

        <div class="col-span-1">
          <label for="amount_cap" class="font-medium block text-base mb-2">
            Campaign amount cap
          </label>
          <input
            type="number"
            id="amount_cap"
            placeholder="$0.00"
            v-model="payload.amount_cap"
            class="text-base p-4 rounded-md font-normal w-full outline-none ring-0 bg-[#FAFAFA]"
          />
          <label class="flex mt-2 items-center space-x-2 justify-start">
            <Checkbox />
            <span> unlimited </span>
          </label>
        </div>

        <div class="col-span-1">
          <label for="conditional_cva" class="font-medium block text-base mb-2">
            Active conditional CVA
          </label>
          <input
            type="number"
            id="conditional_cva"
            placeholder="0"
            v-model="payload.amount_cap"
            class="text-base p-4 rounded-md font-normal w-full outline-none ring-0 bg-[#FAFAFA]"
          />
          <label class="flex mt-2 items-center space-x-2 justify-start">
            <Checkbox />
            <span> unlimited </span>
          </label>
        </div>

        <div class="col-span-1">
          <label
            for="unconditional_cva"
            class="font-medium block text-base mb-2"
          >
            Active unconditional CVA
          </label>
          <input
            type="number"
            id="unconditional_cva"
            placeholder="0"
            v-model="payload.unconditional_cva"
            class="text-base p-4 rounded-md font-normal w-full outline-none ring-0 bg-[#FAFAFA]"
          />
          <label class="flex mt-2 items-center space-x-2 justify-start">
            <Checkbox />
            <span> unlimited </span>
          </label>
        </div>

        <div class="col-span-1">
          <label
            for="total_beneficiaries"
            class="font-medium block text-base mb-2"
          >
            Total beneficiaries
          </label>
          <input
            type="number"
            id="total_beneficiaries"
            placeholder="0"
            v-model="payload.total_beneficiaries"
            class="text-base p-4 rounded-md font-normal w-full outline-none ring-0 bg-[#FAFAFA]"
          />
          <label class="flex mt-2 items-center space-x-2 justify-start">
            <Checkbox />
            <span> unlimited </span>
          </label>
        </div>

        <div class="col-span-1">
          <label
            for="beneficiary_self_unboarding"
            class="font-medium block text-base mb-2"
          >
            Beneficiary self onboarding
          </label>
          <input
            type="number"
            id="beneficiary_self_unboarding"
            placeholder="0"
            v-model="payload.name"
            class="text-base p-4 rounded-md font-normal w-full outline-none ring-0 bg-[#FAFAFA]"
          />
        </div>

        <div class="col-span-1">
          <label for="anual_cost" class="font-medium block text-base mb-2">
            Plan Cost per year
          </label>
          <input
            type="number"
            id="anual_cost"
            placeholder="$0.00"
            v-model="payload.anual_cost"
            class="text-base p-4 rounded-md font-normal w-full outline-none ring-0 bg-[#FAFAFA]"
          />
          <label class="flex mt-2 items-center space-x-2 justify-start">
            <Checkbox />
            <span> unlimited </span>
          </label>
        </div>
      </div>

      <!--  -->
      <div class="grid grid-cols-2 gap-4 mb-4 mt-2">
        <span class="col-span-2 block -mb-2 font-medium">Features</span>

        <div class="col-span-1 space-y-5">
          <label
            for="staistics"
            class="flex mt-2 items-center space-x-2 justify-start"
          >
            <!-- v-model="payload.features.staistics" -->
            <Checkbox />
            <span> Campaign statistics </span>
          </label>

          <label
            for="autogenerated_reports"
            class="flex mt-2 items-center space-x-2 justify-start"
          >
            <!-- v-model="payload.features.autogenerated_reports" -->
            <Checkbox />
            <span> Autogenerated reports </span>
          </label>
        </div>

        <div class="col-span-1 space-y-5">
          <label
            for="support_team"
            class="flex mt-2 items-center space-x-2 justify-start"
          >
            <!-- v-model="payload.features.support_team" -->
            <Checkbox />
            <span> Dedicated support team </span>
          </label>

          <label
            for="staff_training"
            class="flex mt-2 items-center space-x-2 justify-start"
          >
            <!-- v-model="payload.features.staff_training" -->
            <Checkbox />
            <span> Staff Training </span>
          </label>

          <label
            for="certification"
            class="flex mt-2 items-center space-x-2 justify-start"
          >
            <Checkbox :value="payload.features.certification" />
            <span> CHATS certification </span>
          </label>
        </div>
      </div>

      <div class="save-btn flex pb-3 mt-8">
        <Button
          type="submit"
          :has-icon="false"
          :text="action == 'new' ? 'Create plan' : 'Save changes'"
          custom-styles="height:50px; "
          class="px-8"
        />
      </div>
    </form>
  </div>
</template>


<script setup lang="ts">  
const props = defineProps({
  id: {
    type: String,
    default: "button",
  },
  action: {
    type: String,
    default: "button",
  },

},)


const payload = ref({
  name: "",
  amount_cap: "",
  conditional_cva: "",
  unconditional_cva: "",
  total_beneficiaries: "",
  beneficiary_self_unboarding: "",
  anual_cost: "",
  features: {
    staff_training: false,
    staistics: false,
    autogenerated_reports: false,
    certification: false,
    support_team: false
  }
})

const addVendor = () => {
  console.log(payload.value)
} 
</script>
 

 
<style lang="scss" scoped>
/* Chrome, Safari, Edge, Opera */
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

/* Firefox */
input[type="number"] {
  -moz-appearance: textfield;
}</style>
